### ISSUE TITLE
Question: How are non-TOR crawlers used in ail-framework

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-splash-manager#2]
Hi @Terrtia ,
regarding the possibility to also configure crawlers to connect via http proxy. How does the ail-framework know which crawlers on which port can be used for non-TOR connections? Does it need a special configuration in `/ail-framework/configs/core.cfg` under ```
[Crawler]
activate_crawler = True
crawler_depth_limit = 1
...
```
?

**Comment by Terrtia** [comment]
AIL crawler has been upgraded to [Lacus](https://github.com/ail-project/lacus)
Lacus use the default address IP or a proxy if provided in the UI.
